// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAPC4M8ihay34f9dl0tMaIbAZmAOnxQ24',
    appId: '1:1030089657208:web:a5cbdff08220ef30f4168d',
    messagingSenderId: '1030089657208',
    projectId: 'blog-app-96bbc',
    authDomain: 'blog-app-96bbc.firebaseapp.com',
    storageBucket: 'blog-app-96bbc.firebasestorage.app',
    measurementId: 'G-HC7S6FBF65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlcsM8kvetuEeeW2xYYm4VKaM-xAoB21I',
    appId: '1:1030089657208:android:be8ad2d5ad05e3d1f4168d',
    messagingSenderId: '1030089657208',
    projectId: 'blog-app-96bbc',
    storageBucket: 'blog-app-96bbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG13Uajt2oYAzPkUpFwMGitMWUjahqk6g',
    appId: '1:1030089657208:ios:1ae32dc84e04f3bff4168d',
    messagingSenderId: '1030089657208',
    projectId: 'blog-app-96bbc',
    storageBucket: 'blog-app-96bbc.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG13Uajt2oYAzPkUpFwMGitMWUjahqk6g',
    appId: '1:1030089657208:ios:1ae32dc84e04f3bff4168d',
    messagingSenderId: '1030089657208',
    projectId: 'blog-app-96bbc',
    storageBucket: 'blog-app-96bbc.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAPC4M8ihay34f9dl0tMaIbAZmAOnxQ24',
    appId: '1:1030089657208:web:23382ab0a2c2c5e0f4168d',
    messagingSenderId: '1030089657208',
    projectId: 'blog-app-96bbc',
    authDomain: 'blog-app-96bbc.firebaseapp.com',
    storageBucket: 'blog-app-96bbc.firebasestorage.app',
    measurementId: 'G-3BL266DX4X',
  );
}
